### PR TITLE
Add binding for LayoutSaver class

### PR DESCRIPTION
**Pull request by JPatriceR**
Added a missing binding for python.

### CODE REVIEW

**Comment by renatofilho** [comment]
Could you add the LayoutSaver.h into the PyKDDockWidgets_DEPENDS list in CMakeLists.txt ?

**Comment by JPatriceR** [comment]
> Could you add the LayoutSaver.h into the PyKDDockWidgets_DEPENDS list in CMakeLists.txt ?

done :)

**Comment by winterz** [comment]
@JPatriceR  we very much appreciate you contribution; however, we cannot accept your patch until you sign the copyright assignment form. Please see doc/KDDockWidgets-CopyrightAssignmentForm.docx in this repository.

you can email the signed copy to info@kdab.com
Feel free to use a tool like adobe acrobat to draw your signature

**Comment by tardyp** [comment]
Hi @winterz I am Pierre Tardy and I lead the Open-Source Program for Renault Group.

I am afraid we will spend more time involving legal, and bothering our managers authorised to sign such a CLA than it took JP to write those 6 lines of makefiles.
We can argue that those 6 lines are not copyrightable as there is no way any man of the art would implement the feature "Add binding for LayoutSaver class" differently.


I'll refer to https://drewdevault.com/2018/10/05/Dont-sign-a-CLA.html which recommend avoiding signing CLA.

I can see that this project, which technically is quite impressive and valuable has only 15 contributors. I would argue that this is probably due to the CLA.

I can also recognise the difficulty to build business model with OSS and certainly sympathise with you.

**Comment by iamsergio** [comment]
Thanks for the patch Pierre!

FWIW I also agree CLAs are annoying in general (but it's the best way we found to be able to also release as GPL)

Your patch was discussed internally and it's trivial enough to be merged without CLA.

**Comment by tardyp** [comment]
Thanks for your undestanding, and Thanks to @JPatriceR for the actual work. My only contribution was rambling :)

**Pull request merged**
