### PR TITLE
improvements: configurable minimal sizes and central frame; fixes: include-paths and flags

### PR DESCRIPTION
**Pull request by eringerli**
# 87618bbec1b48f184aed67aa6f5bd15d7461ee63
I use KDDockWidgets in a project with qmake (with a simple `INCLUDES+=path-to-kddockwidgets`) and use a custom WidgetFactory. Without relative paths, this generates a lot of errors about not-found files. I also think, that polluting the `include`-paths of the compiler with `private/` is not a very sensible thing to do.

# e371582c9ee5d7a7957b47f0665e8a8ae106f49b
Just a bugfix

# e8c3cff6fbe8464ca7b5ddb30c6e9387d9caa855
This just makes sense, as hardcoding the sizes as `#defines` is IMHO not very user-friendly. I use KDDockWidgets in a project with many docks (+30), so screen area is premium, especially if you have docks with just one label in it to display some changing value.

# b9a0818e191c9b7b4bea436d3169e50a48560000
A new method FrameworkWidgetFactory::createCentralFrame() is added, so it is possible to do add a custom Frame as central frame. This makes it also possible do set custom flags to it, so it is possible to have a central frame without tab bar.

### CODE REVIEW

**Comment by iamsergio** [comment]
will look at this soon, been busy with the layout engine rewrite

**Comment by eringerli** [comment]
I'll rebase it soon to make it compatible with the latest changes

**Comment by eringerli** [comment]
Is there any need for this PR anymore? You changed a lot of stuff, so I want to ask what did you implement already?

- Obvously the fix with the same flag.
- What about the `#includes` with the missing "private/" or relative paths?
- Did you remove the `#defines` for the hardcoded sizes?
- Is it possible to have a custom central frame now? I use that for removing the tab-bar, so allowing for that to be hidden would be enough for me.

**Comment by iamsergio** [comment]
> * Did you remove the `#defines` for the hardcoded sizes?
> * Is it possible to have a custom central frame now? I use that for removing the tab-bar, so allowing for that to be hidden would be enough for me.

The last two no, but I'll do them today, sounds trivial

**Comment by iamsergio** [comment]
- I've pushed Config::setAbsoluteWidgetMinSize(), the the Separator width can be changed too.
- For the custom central frame you can just override createFrame() and pass the flags you need if it's a central frame.
- Not really convinced about the private includes thing. private/ is only in the include path when building KDDW itself. It won't pollute the user's include path.

**Comment by eringerli** [comment]
Thanks, that helps a lot.

About the last point: my project was built with qmake, so I set the include path of the compiler only to the install-path of the includes, not the `private/` too. I will look at it again if I use the upstream again. I recently switched to cmake, so it shouldn't be needed anyway.

**Pull request closed without merging**
